// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoulafLPC_AQTXv6oqElUj7CjTpMFkdn4',
    appId: '1:193647970588:web:19ace9278f908fb8be12d9',
    messagingSenderId: '193647970588',
    projectId: 'shev-weather',
    authDomain: 'shev-weather.firebaseapp.com',
    storageBucket: 'shev-weather.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeycUMaTEp1Yj-roYbGyTLHwvtVCnbNV0',
    appId: '1:193647970588:android:49d4c659489c2721be12d9',
    messagingSenderId: '193647970588',
    projectId: 'shev-weather',
    storageBucket: 'shev-weather.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWd_8lJgWncmskZdtOifyEMVSUJFuCXMk',
    appId: '1:193647970588:ios:0615a684cb4cebc7be12d9',
    messagingSenderId: '193647970588',
    projectId: 'shev-weather',
    storageBucket: 'shev-weather.appspot.com',
    iosClientId: '193647970588-o504fcurgu0tb12v14raouq0csaghf82.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWd_8lJgWncmskZdtOifyEMVSUJFuCXMk',
    appId: '1:193647970588:ios:0615a684cb4cebc7be12d9',
    messagingSenderId: '193647970588',
    projectId: 'shev-weather',
    storageBucket: 'shev-weather.appspot.com',
    iosClientId: '193647970588-o504fcurgu0tb12v14raouq0csaghf82.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
